language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=master@5cc1f1d; TYPE=coverage
      php: 5.6
    - env: DB=mysql; MW=1.23.6;
      php: 5.4
    - env: DB=sqlite; MW=1.23.6;
      php: 5.5
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: THENEEDFORTHIS=FAIL

install:
  - bash ./build/install-mediawiki.sh
  - bash ./build/install-semantic-breadcrumb-links.sh

script:
  - bash ./build/run-tests.sh

after_success:
  - bash ./build/upload-coverage-report.sh
