# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=REL1_29; TYPE=coverage
      php: 5.6
    - env: DB=sqlite; MW=REL1_27; SITELANG=ja
      php: 5.6
    - env: DB=mysql; MW=REL1_30; PHPUNIT=4.8.*
      php: 7.1
    - env: DB=mysql; MW=REL1_31; PHPUNIT=6.5.*
      php: 7.1
    - env: DB=sqlite; MW=master; PHPUNIT=7.3.*
      php: 7.2

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-breadcrumb-links.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
